-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mul is
port (
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (16 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of mul is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal mul_ln93_fu_24_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln93_fu_24_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln93_fu_24_p00 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &mul_ln93_fu_24_p0) * signed(mul_ln93_fu_24_p1))), 32));
    mul_ln93_fu_24_p0 <= mul_ln93_fu_24_p00(17 - 1 downto 0);
    mul_ln93_fu_24_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b),32));
    mul_ln93_fu_24_p1 <= a;
end behav;
