-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vector_matrix_mul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_vec_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_vec_ce0 : OUT STD_LOGIC;
    output_vec_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_vec_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_vec_ce1 : OUT STD_LOGIC;
    output_vec_we1 : OUT STD_LOGIC;
    output_vec_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    S_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    S_ce0 : OUT STD_LOGIC;
    S_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_we0 : OUT STD_LOGIC;
    A_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    A_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_1_ce1 : OUT STD_LOGIC;
    A_1_we1 : OUT STD_LOGIC;
    A_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    A_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_2_ce0 : OUT STD_LOGIC;
    A_2_we0 : OUT STD_LOGIC;
    A_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    A_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_2_ce1 : OUT STD_LOGIC;
    A_2_we1 : OUT STD_LOGIC;
    A_2_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    E_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    E_ce0 : OUT STD_LOGIC;
    E_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    sk_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    sk_ce0 : OUT STD_LOGIC;
    sk_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    seed_A_separated_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    seed_A_separated_ce0 : OUT STD_LOGIC;
    seed_A_separated_we0 : OUT STD_LOGIC;
    seed_A_separated_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    seed_A_separated_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    seed_A_separated_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    seed_A_separated_ce1 : OUT STD_LOGIC;
    seed_A_separated_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    pregen : IN STD_LOGIC_VECTOR (0 downto 0);
    n : IN STD_LOGIC_VECTOR (10 downto 0);
    use_A : IN STD_LOGIC_VECTOR (3 downto 0);
    begin_r : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of vector_matrix_mul is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv18_10 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000010000";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv10_280 : STD_LOGIC_VECTOR (9 downto 0) := "1010000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_27F : STD_LOGIC_VECTOR (9 downto 0) := "1001111111";
    constant ap_const_lv17_18 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000011000";
    constant ap_const_lv17_10 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_const_lv16_F : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001111";
    constant ap_const_lv10_27E : STD_LOGIC_VECTOR (9 downto 0) := "1001111110";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal begin_read_read_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln467_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln467_reg_484 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln471_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln471_reg_488 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln502_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln502_reg_492 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_frodo_unpack_8_fu_293_ap_ready : STD_LOGIC;
    signal grp_frodo_unpack_8_fu_293_ap_done : STD_LOGIC;
    signal ap_predicate_op30_call_state2 : BOOLEAN;
    signal grp_shake128_10240_fu_234_ap_ready : STD_LOGIC;
    signal grp_shake128_10240_fu_234_ap_done : STD_LOGIC;
    signal ap_predicate_op32_call_state2 : BOOLEAN;
    signal grp_read_S_fu_325_ap_ready : STD_LOGIC;
    signal grp_read_S_fu_325_ap_done : STD_LOGIC;
    signal ap_predicate_op35_call_state2 : BOOLEAN;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal icmp_ln507_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln507_reg_496 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln524_fu_367_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln524_reg_500 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln486_fu_370_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln486_reg_505 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal offset_S_fu_380_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal offset_S_reg_512 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln486_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal offset_S_1_fu_397_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal offset_S_1_reg_522 : STD_LOGIC_VECTOR (9 downto 0);
    signal temp_reg_527 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln514_1_fu_420_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln514_1_reg_532 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln533_1_fu_435_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln533_1_reg_537 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln539_fu_453_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_predicate_op83_call_state5 : BOOLEAN;
    signal grp_scalar_vector_mul_fu_309_ap_ready : STD_LOGIC;
    signal grp_scalar_vector_mul_fu_309_ap_done : STD_LOGIC;
    signal ap_predicate_op84_call_state5 : BOOLEAN;
    signal ap_predicate_op87_call_state5 : BOOLEAN;
    signal ap_predicate_op88_call_state5 : BOOLEAN;
    signal ap_predicate_op90_call_state5 : BOOLEAN;
    signal ap_predicate_op91_call_state5 : BOOLEAN;
    signal ap_predicate_op93_call_state5 : BOOLEAN;
    signal ap_predicate_op94_call_state5 : BOOLEAN;
    signal ap_predicate_op96_call_state5 : BOOLEAN;
    signal ap_predicate_op97_call_state5 : BOOLEAN;
    signal ap_predicate_op100_call_state5 : BOOLEAN;
    signal ap_predicate_op101_call_state5 : BOOLEAN;
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal grp_shake128_10240_fu_234_ap_start : STD_LOGIC;
    signal grp_shake128_10240_fu_234_ap_idle : STD_LOGIC;
    signal grp_shake128_10240_fu_234_output_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_shake128_10240_fu_234_output_r_ce0 : STD_LOGIC;
    signal grp_shake128_10240_fu_234_output_r_we0 : STD_LOGIC;
    signal grp_shake128_10240_fu_234_output_r_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_shake128_10240_fu_234_output_r_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_shake128_10240_fu_234_output_r_ce1 : STD_LOGIC;
    signal grp_shake128_10240_fu_234_output_r_we1 : STD_LOGIC;
    signal grp_shake128_10240_fu_234_output_r_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_shake128_10240_fu_234_input_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_shake128_10240_fu_234_input_r_ce0 : STD_LOGIC;
    signal grp_shake128_10240_fu_234_input_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_shake128_10240_fu_234_input_r_ce1 : STD_LOGIC;
    signal grp_frodo_unpack_8_fu_293_ap_start : STD_LOGIC;
    signal grp_frodo_unpack_8_fu_293_ap_idle : STD_LOGIC;
    signal grp_frodo_unpack_8_fu_293_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_frodo_unpack_8_fu_293_out_r_ce0 : STD_LOGIC;
    signal grp_frodo_unpack_8_fu_293_out_r_we0 : STD_LOGIC;
    signal grp_frodo_unpack_8_fu_293_out_r_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_frodo_unpack_8_fu_293_in_r_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_frodo_unpack_8_fu_293_in_r_ce0 : STD_LOGIC;
    signal grp_frodo_unpack_8_fu_293_in_offset : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_frodo_unpack_8_fu_293_rest_len : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_scalar_vector_mul_fu_309_ap_start : STD_LOGIC;
    signal grp_scalar_vector_mul_fu_309_ap_idle : STD_LOGIC;
    signal grp_scalar_vector_mul_fu_309_output_vec_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_scalar_vector_mul_fu_309_output_vec_ce0 : STD_LOGIC;
    signal grp_scalar_vector_mul_fu_309_output_vec_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_scalar_vector_mul_fu_309_output_vec_ce1 : STD_LOGIC;
    signal grp_scalar_vector_mul_fu_309_output_vec_we1 : STD_LOGIC;
    signal grp_scalar_vector_mul_fu_309_output_vec_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_scalar_vector_mul_fu_309_input_vec_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_scalar_vector_mul_fu_309_input_vec_ce0 : STD_LOGIC;
    signal grp_scalar_vector_mul_fu_309_input_vec_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_scalar_vector_mul_fu_309_E_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_scalar_vector_mul_fu_309_E_ce0 : STD_LOGIC;
    signal grp_read_S_fu_325_ap_start : STD_LOGIC;
    signal grp_read_S_fu_325_ap_idle : STD_LOGIC;
    signal grp_read_S_fu_325_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_read_S_fu_325_out_r_ce0 : STD_LOGIC;
    signal grp_read_S_fu_325_out_r_we0 : STD_LOGIC;
    signal grp_read_S_fu_325_out_r_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_read_S_fu_325_in_r_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_read_S_fu_325_in_r_ce0 : STD_LOGIC;
    signal grp_read_S_fu_325_offset : STD_LOGIC_VECTOR (9 downto 0);
    signal i_0_reg_194 : STD_LOGIC_VECTOR (9 downto 0);
    signal offset_B_0_reg_206 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_offset_B_3_phi_fu_221_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal offset_B_fu_440_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_shake128_10240_fu_234_ap_start_reg : STD_LOGIC := '0';
    signal grp_frodo_unpack_8_fu_293_ap_start_reg : STD_LOGIC := '0';
    signal grp_scalar_vector_mul_fu_309_ap_start_reg : STD_LOGIC := '0';
    signal grp_read_S_fu_325_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln488_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln467_fu_336_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln502_fu_352_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln489_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln514_fu_410_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln514_fu_414_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln533_fu_425_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln533_fu_429_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln539_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);

    component shake128_10240 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        output_r_ce1 : OUT STD_LOGIC;
        output_r_we1 : OUT STD_LOGIC;
        output_r_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        input_r_ce1 : OUT STD_LOGIC;
        input_r_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component frodo_unpack_8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        in_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        in_r_ce0 : OUT STD_LOGIC;
        in_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        in_offset : IN STD_LOGIC_VECTOR (17 downto 0);
        rest_len : IN STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component scalar_vector_mul IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_vec_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        output_vec_ce0 : OUT STD_LOGIC;
        output_vec_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        output_vec_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        output_vec_ce1 : OUT STD_LOGIC;
        output_vec_we1 : OUT STD_LOGIC;
        output_vec_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_vec_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        input_vec_ce0 : OUT STD_LOGIC;
        input_vec_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        scalar : IN STD_LOGIC_VECTOR (15 downto 0);
        n : IN STD_LOGIC_VECTOR (9 downto 0);
        index : IN STD_LOGIC_VECTOR (9 downto 0);
        E_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        E_ce0 : OUT STD_LOGIC;
        E_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component read_S IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        in_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        in_r_ce0 : OUT STD_LOGIC;
        in_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        offset : IN STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    grp_shake128_10240_fu_234 : component shake128_10240
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_shake128_10240_fu_234_ap_start,
        ap_done => grp_shake128_10240_fu_234_ap_done,
        ap_idle => grp_shake128_10240_fu_234_ap_idle,
        ap_ready => grp_shake128_10240_fu_234_ap_ready,
        output_r_address0 => grp_shake128_10240_fu_234_output_r_address0,
        output_r_ce0 => grp_shake128_10240_fu_234_output_r_ce0,
        output_r_we0 => grp_shake128_10240_fu_234_output_r_we0,
        output_r_d0 => grp_shake128_10240_fu_234_output_r_d0,
        output_r_address1 => grp_shake128_10240_fu_234_output_r_address1,
        output_r_ce1 => grp_shake128_10240_fu_234_output_r_ce1,
        output_r_we1 => grp_shake128_10240_fu_234_output_r_we1,
        output_r_d1 => grp_shake128_10240_fu_234_output_r_d1,
        input_r_address0 => grp_shake128_10240_fu_234_input_r_address0,
        input_r_ce0 => grp_shake128_10240_fu_234_input_r_ce0,
        input_r_q0 => seed_A_separated_q0,
        input_r_address1 => grp_shake128_10240_fu_234_input_r_address1,
        input_r_ce1 => grp_shake128_10240_fu_234_input_r_ce1,
        input_r_q1 => seed_A_separated_q1);

    grp_frodo_unpack_8_fu_293 : component frodo_unpack_8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_frodo_unpack_8_fu_293_ap_start,
        ap_done => grp_frodo_unpack_8_fu_293_ap_done,
        ap_idle => grp_frodo_unpack_8_fu_293_ap_idle,
        ap_ready => grp_frodo_unpack_8_fu_293_ap_ready,
        out_r_address0 => grp_frodo_unpack_8_fu_293_out_r_address0,
        out_r_ce0 => grp_frodo_unpack_8_fu_293_out_r_ce0,
        out_r_we0 => grp_frodo_unpack_8_fu_293_out_r_we0,
        out_r_d0 => grp_frodo_unpack_8_fu_293_out_r_d0,
        in_r_address0 => grp_frodo_unpack_8_fu_293_in_r_address0,
        in_r_ce0 => grp_frodo_unpack_8_fu_293_in_r_ce0,
        in_r_q0 => sk_q0,
        in_offset => grp_frodo_unpack_8_fu_293_in_offset,
        rest_len => grp_frodo_unpack_8_fu_293_rest_len);

    grp_scalar_vector_mul_fu_309 : component scalar_vector_mul
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_scalar_vector_mul_fu_309_ap_start,
        ap_done => grp_scalar_vector_mul_fu_309_ap_done,
        ap_idle => grp_scalar_vector_mul_fu_309_ap_idle,
        ap_ready => grp_scalar_vector_mul_fu_309_ap_ready,
        output_vec_address0 => grp_scalar_vector_mul_fu_309_output_vec_address0,
        output_vec_ce0 => grp_scalar_vector_mul_fu_309_output_vec_ce0,
        output_vec_q0 => output_vec_q0,
        output_vec_address1 => grp_scalar_vector_mul_fu_309_output_vec_address1,
        output_vec_ce1 => grp_scalar_vector_mul_fu_309_output_vec_ce1,
        output_vec_we1 => grp_scalar_vector_mul_fu_309_output_vec_we1,
        output_vec_d1 => grp_scalar_vector_mul_fu_309_output_vec_d1,
        input_vec_address0 => grp_scalar_vector_mul_fu_309_input_vec_address0,
        input_vec_ce0 => grp_scalar_vector_mul_fu_309_input_vec_ce0,
        input_vec_q0 => grp_scalar_vector_mul_fu_309_input_vec_q0,
        scalar => temp_reg_527,
        n => trunc_ln524_reg_500,
        index => i_0_reg_194,
        E_address0 => grp_scalar_vector_mul_fu_309_E_address0,
        E_ce0 => grp_scalar_vector_mul_fu_309_E_ce0,
        E_q0 => E_q0);

    grp_read_S_fu_325 : component read_S
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read_S_fu_325_ap_start,
        ap_done => grp_read_S_fu_325_ap_done,
        ap_idle => grp_read_S_fu_325_ap_idle,
        ap_ready => grp_read_S_fu_325_ap_ready,
        out_r_address0 => grp_read_S_fu_325_out_r_address0,
        out_r_ce0 => grp_read_S_fu_325_out_r_ce0,
        out_r_we0 => grp_read_S_fu_325_out_r_we0,
        out_r_d0 => grp_read_S_fu_325_out_r_d0,
        in_r_address0 => grp_read_S_fu_325_in_r_address0,
        in_r_ce0 => grp_read_S_fu_325_in_r_ce0,
        in_r_q0 => sk_q0,
        offset => grp_read_S_fu_325_offset);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_frodo_unpack_8_fu_293_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_frodo_unpack_8_fu_293_ap_start_reg <= ap_const_logic_0;
            else
                if ((((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln471_fu_346_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (icmp_ln467_fu_340_p2 = ap_const_lv1_0) and (pregen = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0)))) then 
                    grp_frodo_unpack_8_fu_293_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_frodo_unpack_8_fu_293_ap_ready = ap_const_logic_1)) then 
                    grp_frodo_unpack_8_fu_293_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_read_S_fu_325_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read_S_fu_325_ap_start_reg <= ap_const_logic_0;
            else
                if ((((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (icmp_ln467_fu_340_p2 = ap_const_lv1_1) and (pregen = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln502_reg_492 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_1)))) then 
                    grp_read_S_fu_325_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read_S_fu_325_ap_ready = ap_const_logic_1)) then 
                    grp_read_S_fu_325_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_scalar_vector_mul_fu_309_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_scalar_vector_mul_fu_309_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln502_reg_492 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln507_reg_496 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0)))) then 
                    grp_scalar_vector_mul_fu_309_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_scalar_vector_mul_fu_309_ap_ready = ap_const_logic_1)) then 
                    grp_scalar_vector_mul_fu_309_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_shake128_10240_fu_234_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_shake128_10240_fu_234_ap_start_reg <= ap_const_logic_0;
            else
                if ((((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (icmp_ln471_fu_346_p2 = ap_const_lv1_1) and (icmp_ln467_fu_340_p2 = ap_const_lv1_0) and (pregen = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln507_reg_496 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_1)))) then 
                    grp_shake128_10240_fu_234_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_shake128_10240_fu_234_ap_ready = ap_const_logic_1)) then 
                    grp_shake128_10240_fu_234_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_0_reg_194 <= offset_S_reg_512;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then 
                i_0_reg_194 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    offset_B_0_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                offset_B_0_reg_206 <= select_ln539_fu_453_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then 
                offset_B_0_reg_206 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (pregen = ap_const_lv1_1))) then
                icmp_ln467_reg_484 <= icmp_ln467_fu_340_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (icmp_ln467_fu_340_p2 = ap_const_lv1_0) and (pregen = ap_const_lv1_1))) then
                icmp_ln471_reg_488 <= icmp_ln471_fu_346_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                icmp_ln502_reg_492 <= icmp_ln502_fu_355_p2;
                icmp_ln507_reg_496 <= icmp_ln507_fu_361_p2;
                trunc_ln524_reg_500 <= trunc_ln524_fu_367_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln486_fu_374_p2 = ap_const_lv1_0))) then
                offset_S_1_reg_522 <= offset_S_1_fu_397_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                offset_S_reg_512 <= offset_S_fu_380_p2;
                trunc_ln486_reg_505 <= trunc_ln486_fu_370_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                temp_reg_527 <= S_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0))) then
                    zext_ln514_1_reg_532(16 downto 0) <= zext_ln514_1_fu_420_p1(16 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1))) then
                    zext_ln533_1_reg_537(16 downto 0) <= zext_ln533_1_fu_435_p1(16 downto 0);
            end if;
        end if;
    end process;
    zext_ln514_1_reg_532(17) <= '0';
    zext_ln533_1_reg_537(17) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, begin_read_read_fu_144_p2, ap_CS_fsm_state2, ap_block_state2_on_subcall_done, ap_CS_fsm_state3, icmp_ln486_fu_374_p2, ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((begin_read_read_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((begin_read_read_fu_144_p2 = ap_const_lv1_0) or (icmp_ln486_fu_374_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    A_1_address0_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op87_call_state5, ap_predicate_op90_call_state5, ap_predicate_op94_call_state5, ap_predicate_op97_call_state5, ap_predicate_op101_call_state5, grp_shake128_10240_fu_234_output_r_address0, grp_frodo_unpack_8_fu_293_out_r_address0, grp_scalar_vector_mul_fu_309_input_vec_address0, grp_read_S_fu_325_out_r_address0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op90_call_state5 = ap_const_boolean_1))) then 
            A_1_address0 <= grp_read_S_fu_325_out_r_address0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)))) then 
            A_1_address0 <= grp_scalar_vector_mul_fu_309_input_vec_address0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op83_call_state5 = ap_const_boolean_1))) then 
            A_1_address0 <= grp_frodo_unpack_8_fu_293_out_r_address0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op87_call_state5 = ap_const_boolean_1))) then 
            A_1_address0 <= grp_shake128_10240_fu_234_output_r_address0;
        else 
            A_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;

    A_1_address1 <= grp_shake128_10240_fu_234_output_r_address1;

    A_1_ce0_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op87_call_state5, ap_predicate_op90_call_state5, ap_predicate_op94_call_state5, ap_predicate_op97_call_state5, ap_predicate_op101_call_state5, grp_shake128_10240_fu_234_output_r_ce0, grp_frodo_unpack_8_fu_293_out_r_ce0, grp_scalar_vector_mul_fu_309_input_vec_ce0, grp_read_S_fu_325_out_r_ce0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op90_call_state5 = ap_const_boolean_1))) then 
            A_1_ce0 <= grp_read_S_fu_325_out_r_ce0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)))) then 
            A_1_ce0 <= grp_scalar_vector_mul_fu_309_input_vec_ce0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op83_call_state5 = ap_const_boolean_1))) then 
            A_1_ce0 <= grp_frodo_unpack_8_fu_293_out_r_ce0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op87_call_state5 = ap_const_boolean_1))) then 
            A_1_ce0 <= grp_shake128_10240_fu_234_output_r_ce0;
        else 
            A_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_1_ce1_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op87_call_state5, grp_shake128_10240_fu_234_output_r_ce1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op87_call_state5 = ap_const_boolean_1))) then 
            A_1_ce1 <= grp_shake128_10240_fu_234_output_r_ce1;
        else 
            A_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    A_1_d0_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op87_call_state5, ap_predicate_op90_call_state5, grp_shake128_10240_fu_234_output_r_d0, grp_frodo_unpack_8_fu_293_out_r_d0, grp_read_S_fu_325_out_r_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
            if ((ap_predicate_op90_call_state5 = ap_const_boolean_1)) then 
                A_1_d0 <= grp_read_S_fu_325_out_r_d0;
            elsif ((ap_predicate_op83_call_state5 = ap_const_boolean_1)) then 
                A_1_d0 <= grp_frodo_unpack_8_fu_293_out_r_d0;
            elsif ((ap_predicate_op87_call_state5 = ap_const_boolean_1)) then 
                A_1_d0 <= grp_shake128_10240_fu_234_output_r_d0;
            else 
                A_1_d0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            A_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    A_1_d1 <= grp_shake128_10240_fu_234_output_r_d1;

    A_1_we0_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op87_call_state5, ap_predicate_op90_call_state5, grp_shake128_10240_fu_234_output_r_we0, grp_frodo_unpack_8_fu_293_out_r_we0, grp_read_S_fu_325_out_r_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
            if ((ap_predicate_op90_call_state5 = ap_const_boolean_1)) then 
                A_1_we0 <= grp_read_S_fu_325_out_r_we0;
            elsif ((ap_predicate_op83_call_state5 = ap_const_boolean_1)) then 
                A_1_we0 <= grp_frodo_unpack_8_fu_293_out_r_we0;
            elsif ((ap_predicate_op87_call_state5 = ap_const_boolean_1)) then 
                A_1_we0 <= grp_shake128_10240_fu_234_output_r_we0;
            else 
                A_1_we0 <= ap_const_logic_0;
            end if;
        else 
            A_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    A_1_we1_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op87_call_state5, grp_shake128_10240_fu_234_output_r_we1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op87_call_state5 = ap_const_boolean_1))) then 
            A_1_we1 <= grp_shake128_10240_fu_234_output_r_we1;
        else 
            A_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    A_2_address0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, ap_predicate_op32_call_state2, ap_predicate_op35_call_state2, ap_CS_fsm_state5, ap_predicate_op84_call_state5, ap_predicate_op88_call_state5, ap_predicate_op91_call_state5, ap_predicate_op93_call_state5, ap_predicate_op96_call_state5, ap_predicate_op100_call_state5, grp_shake128_10240_fu_234_output_r_address0, grp_frodo_unpack_8_fu_293_out_r_address0, grp_scalar_vector_mul_fu_309_input_vec_address0, grp_read_S_fu_325_out_r_address0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op35_call_state2 = ap_const_boolean_1)))) then 
            A_2_address0 <= grp_read_S_fu_325_out_r_address0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)))) then 
            A_2_address0 <= grp_scalar_vector_mul_fu_309_input_vec_address0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)))) then 
            A_2_address0 <= grp_frodo_unpack_8_fu_293_out_r_address0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            A_2_address0 <= grp_shake128_10240_fu_234_output_r_address0;
        else 
            A_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;

    A_2_address1 <= grp_shake128_10240_fu_234_output_r_address1;

    A_2_ce0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, ap_predicate_op32_call_state2, ap_predicate_op35_call_state2, ap_CS_fsm_state5, ap_predicate_op84_call_state5, ap_predicate_op88_call_state5, ap_predicate_op91_call_state5, ap_predicate_op93_call_state5, ap_predicate_op96_call_state5, ap_predicate_op100_call_state5, grp_shake128_10240_fu_234_output_r_ce0, grp_frodo_unpack_8_fu_293_out_r_ce0, grp_scalar_vector_mul_fu_309_input_vec_ce0, grp_read_S_fu_325_out_r_ce0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op35_call_state2 = ap_const_boolean_1)))) then 
            A_2_ce0 <= grp_read_S_fu_325_out_r_ce0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)))) then 
            A_2_ce0 <= grp_scalar_vector_mul_fu_309_input_vec_ce0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)))) then 
            A_2_ce0 <= grp_frodo_unpack_8_fu_293_out_r_ce0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            A_2_ce0 <= grp_shake128_10240_fu_234_output_r_ce0;
        else 
            A_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_2_ce1_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op32_call_state2, ap_CS_fsm_state5, ap_predicate_op96_call_state5, grp_shake128_10240_fu_234_output_r_ce1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            A_2_ce1 <= grp_shake128_10240_fu_234_output_r_ce1;
        else 
            A_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    A_2_d0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, ap_predicate_op32_call_state2, ap_predicate_op35_call_state2, ap_CS_fsm_state5, ap_predicate_op93_call_state5, ap_predicate_op96_call_state5, ap_predicate_op100_call_state5, grp_shake128_10240_fu_234_output_r_d0, grp_frodo_unpack_8_fu_293_out_r_d0, grp_read_S_fu_325_out_r_d0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op35_call_state2 = ap_const_boolean_1)))) then 
            A_2_d0 <= grp_read_S_fu_325_out_r_d0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)))) then 
            A_2_d0 <= grp_frodo_unpack_8_fu_293_out_r_d0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            A_2_d0 <= grp_shake128_10240_fu_234_output_r_d0;
        else 
            A_2_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    A_2_d1 <= grp_shake128_10240_fu_234_output_r_d1;

    A_2_we0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, ap_predicate_op32_call_state2, ap_predicate_op35_call_state2, ap_CS_fsm_state5, ap_predicate_op93_call_state5, ap_predicate_op96_call_state5, ap_predicate_op100_call_state5, grp_shake128_10240_fu_234_output_r_we0, grp_frodo_unpack_8_fu_293_out_r_we0, grp_read_S_fu_325_out_r_we0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op35_call_state2 = ap_const_boolean_1)))) then 
            A_2_we0 <= grp_read_S_fu_325_out_r_we0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)))) then 
            A_2_we0 <= grp_frodo_unpack_8_fu_293_out_r_we0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            A_2_we0 <= grp_shake128_10240_fu_234_output_r_we0;
        else 
            A_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    A_2_we1_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op32_call_state2, ap_CS_fsm_state5, ap_predicate_op96_call_state5, grp_shake128_10240_fu_234_output_r_we1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            A_2_we1 <= grp_shake128_10240_fu_234_output_r_we1;
        else 
            A_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    E_address0 <= grp_scalar_vector_mul_fu_309_E_address0;

    E_ce0_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op84_call_state5, ap_predicate_op88_call_state5, ap_predicate_op91_call_state5, ap_predicate_op94_call_state5, ap_predicate_op97_call_state5, ap_predicate_op101_call_state5, grp_scalar_vector_mul_fu_309_E_ce0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)))) then 
            E_ce0 <= grp_scalar_vector_mul_fu_309_E_ce0;
        else 
            E_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    S_address0 <= zext_ln488_fu_386_p1(10 - 1 downto 0);

    S_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            S_ce0 <= ap_const_logic_1;
        else 
            S_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln514_fu_414_p2 <= std_logic_vector(unsigned(zext_ln514_fu_410_p1) + unsigned(ap_const_lv17_18));
    add_ln533_fu_429_p2 <= std_logic_vector(unsigned(zext_ln533_fu_425_p1) + unsigned(ap_const_lv17_10));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state2_on_subcall_done_assign_proc : process(grp_frodo_unpack_8_fu_293_ap_done, ap_predicate_op30_call_state2, grp_shake128_10240_fu_234_ap_done, ap_predicate_op32_call_state2, grp_read_S_fu_325_ap_done, ap_predicate_op35_call_state2)
    begin
                ap_block_state2_on_subcall_done <= (((grp_read_S_fu_325_ap_done = ap_const_logic_0) and (ap_predicate_op35_call_state2 = ap_const_boolean_1)) or ((grp_shake128_10240_fu_234_ap_done = ap_const_logic_0) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)) or ((grp_frodo_unpack_8_fu_293_ap_done = ap_const_logic_0) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)));
    end process;


    ap_block_state5_on_subcall_done_assign_proc : process(grp_frodo_unpack_8_fu_293_ap_done, grp_shake128_10240_fu_234_ap_done, grp_read_S_fu_325_ap_done, ap_predicate_op83_call_state5, grp_scalar_vector_mul_fu_309_ap_done, ap_predicate_op84_call_state5, ap_predicate_op87_call_state5, ap_predicate_op88_call_state5, ap_predicate_op90_call_state5, ap_predicate_op91_call_state5, ap_predicate_op93_call_state5, ap_predicate_op94_call_state5, ap_predicate_op96_call_state5, ap_predicate_op97_call_state5, ap_predicate_op100_call_state5, ap_predicate_op101_call_state5)
    begin
                ap_block_state5_on_subcall_done <= (((grp_scalar_vector_mul_fu_309_ap_done = ap_const_logic_0) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((grp_scalar_vector_mul_fu_309_ap_done = ap_const_logic_0) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((grp_scalar_vector_mul_fu_309_ap_done = ap_const_logic_0) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)) or ((grp_scalar_vector_mul_fu_309_ap_done = ap_const_logic_0) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((grp_scalar_vector_mul_fu_309_ap_done = ap_const_logic_0) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((grp_scalar_vector_mul_fu_309_ap_done = ap_const_logic_0) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)) or ((grp_read_S_fu_325_ap_done = ap_const_logic_0) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((grp_read_S_fu_325_ap_done = ap_const_logic_0) and (ap_predicate_op90_call_state5 = ap_const_boolean_1)) or ((grp_shake128_10240_fu_234_ap_done = ap_const_logic_0) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((grp_shake128_10240_fu_234_ap_done = ap_const_logic_0) and (ap_predicate_op87_call_state5 = ap_const_boolean_1)) or ((grp_frodo_unpack_8_fu_293_ap_done = ap_const_logic_0) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((grp_frodo_unpack_8_fu_293_ap_done = ap_const_logic_0) and (ap_predicate_op83_call_state5 = ap_const_boolean_1)));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, begin_read_read_fu_144_p2, ap_CS_fsm_state3, icmp_ln486_fu_374_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and ((begin_read_read_fu_144_p2 = ap_const_lv1_0) or (icmp_ln486_fu_374_p2 = ap_const_lv1_1))) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_offset_B_3_phi_fu_221_p8_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505, ap_CS_fsm_state5, offset_B_0_reg_206, offset_B_fu_440_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0))) then 
            ap_phi_mux_offset_B_3_phi_fu_221_p8 <= offset_B_fu_440_p2;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (trunc_ln486_reg_505 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_1)))) then 
            ap_phi_mux_offset_B_3_phi_fu_221_p8 <= offset_B_0_reg_206;
        else 
            ap_phi_mux_offset_B_3_phi_fu_221_p8 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_predicate_op100_call_state5_assign_proc : process(icmp_ln502_reg_492, trunc_ln486_reg_505)
    begin
                ap_predicate_op100_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln502_reg_492 = ap_const_lv1_1));
    end process;


    ap_predicate_op101_call_state5_assign_proc : process(icmp_ln502_reg_492, trunc_ln486_reg_505)
    begin
                ap_predicate_op101_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln502_reg_492 = ap_const_lv1_1));
    end process;


    ap_predicate_op30_call_state2_assign_proc : process(pregen, icmp_ln467_reg_484, icmp_ln471_reg_488)
    begin
                ap_predicate_op30_call_state2 <= ((icmp_ln471_reg_488 = ap_const_lv1_0) and (icmp_ln467_reg_484 = ap_const_lv1_0) and (pregen = ap_const_lv1_1));
    end process;


    ap_predicate_op32_call_state2_assign_proc : process(pregen, icmp_ln467_reg_484, icmp_ln471_reg_488)
    begin
                ap_predicate_op32_call_state2 <= ((icmp_ln471_reg_488 = ap_const_lv1_1) and (icmp_ln467_reg_484 = ap_const_lv1_0) and (pregen = ap_const_lv1_1));
    end process;


    ap_predicate_op35_call_state2_assign_proc : process(pregen, icmp_ln467_reg_484)
    begin
                ap_predicate_op35_call_state2 <= ((icmp_ln467_reg_484 = ap_const_lv1_1) and (pregen = ap_const_lv1_1));
    end process;


    ap_predicate_op83_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op83_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0));
    end process;


    ap_predicate_op84_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op84_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0));
    end process;


    ap_predicate_op87_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op87_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_1));
    end process;


    ap_predicate_op88_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op88_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (icmp_ln507_reg_496 = ap_const_lv1_1));
    end process;


    ap_predicate_op90_call_state5_assign_proc : process(icmp_ln502_reg_492, trunc_ln486_reg_505)
    begin
                ap_predicate_op90_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_1));
    end process;


    ap_predicate_op91_call_state5_assign_proc : process(icmp_ln502_reg_492, trunc_ln486_reg_505)
    begin
                ap_predicate_op91_call_state5 <= ((trunc_ln486_reg_505 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_1));
    end process;


    ap_predicate_op93_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op93_call_state5 <= ((icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1));
    end process;


    ap_predicate_op94_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op94_call_state5 <= ((icmp_ln507_reg_496 = ap_const_lv1_0) and (icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1));
    end process;


    ap_predicate_op96_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op96_call_state5 <= ((icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln507_reg_496 = ap_const_lv1_1));
    end process;


    ap_predicate_op97_call_state5_assign_proc : process(icmp_ln502_reg_492, icmp_ln507_reg_496, trunc_ln486_reg_505)
    begin
                ap_predicate_op97_call_state5 <= ((icmp_ln502_reg_492 = ap_const_lv1_0) and (trunc_ln486_reg_505 = ap_const_lv1_1) and (icmp_ln507_reg_496 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(begin_read_read_fu_144_p2, ap_CS_fsm_state3, icmp_ln486_fu_374_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((begin_read_read_fu_144_p2 = ap_const_lv1_0) or (icmp_ln486_fu_374_p2 = ap_const_lv1_1)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    begin_read_read_fu_144_p2 <= begin_r;
    grp_frodo_unpack_8_fu_293_ap_start <= grp_frodo_unpack_8_fu_293_ap_start_reg;

    grp_frodo_unpack_8_fu_293_in_offset_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, zext_ln514_1_reg_532, zext_ln533_1_reg_537, ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op93_call_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1))) then 
            grp_frodo_unpack_8_fu_293_in_offset <= zext_ln533_1_reg_537;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op83_call_state5 = ap_const_boolean_1))) then 
            grp_frodo_unpack_8_fu_293_in_offset <= zext_ln514_1_reg_532;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1))) then 
            grp_frodo_unpack_8_fu_293_in_offset <= ap_const_lv18_10;
        else 
            grp_frodo_unpack_8_fu_293_in_offset <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_frodo_unpack_8_fu_293_rest_len_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op93_call_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op83_call_state5 = ap_const_boolean_1))) then 
            grp_frodo_unpack_8_fu_293_rest_len <= ap_const_lv6_8;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)))) then 
            grp_frodo_unpack_8_fu_293_rest_len <= ap_const_lv6_10;
        else 
            grp_frodo_unpack_8_fu_293_rest_len <= "XXXXXX";
        end if; 
    end process;

    grp_read_S_fu_325_ap_start <= grp_read_S_fu_325_ap_start_reg;

    grp_read_S_fu_325_offset_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op35_call_state2, offset_S_1_reg_522, ap_CS_fsm_state5, ap_predicate_op90_call_state5, ap_predicate_op100_call_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op90_call_state5 = ap_const_boolean_1)))) then 
            grp_read_S_fu_325_offset <= offset_S_1_reg_522;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op35_call_state2 = ap_const_boolean_1))) then 
            grp_read_S_fu_325_offset <= ap_const_lv10_0;
        else 
            grp_read_S_fu_325_offset <= "XXXXXXXXXX";
        end if; 
    end process;

    grp_scalar_vector_mul_fu_309_ap_start <= grp_scalar_vector_mul_fu_309_ap_start_reg;

    grp_scalar_vector_mul_fu_309_input_vec_q0_assign_proc : process(A_1_q0, A_2_q0, ap_CS_fsm_state5, ap_predicate_op84_call_state5, ap_predicate_op88_call_state5, ap_predicate_op91_call_state5, ap_predicate_op94_call_state5, ap_predicate_op97_call_state5, ap_predicate_op101_call_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)))) then 
            grp_scalar_vector_mul_fu_309_input_vec_q0 <= A_1_q0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)))) then 
            grp_scalar_vector_mul_fu_309_input_vec_q0 <= A_2_q0;
        else 
            grp_scalar_vector_mul_fu_309_input_vec_q0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_shake128_10240_fu_234_ap_start <= grp_shake128_10240_fu_234_ap_start_reg;
    icmp_ln467_fu_340_p2 <= "1" when (trunc_ln467_fu_336_p1 = ap_const_lv2_0) else "0";
    icmp_ln471_fu_346_p2 <= "1" when (trunc_ln467_fu_336_p1 = ap_const_lv2_1) else "0";
    icmp_ln486_fu_374_p2 <= "1" when (i_0_reg_194 = ap_const_lv10_280) else "0";
    icmp_ln489_fu_391_p2 <= "1" when (i_0_reg_194 = ap_const_lv10_27F) else "0";
    icmp_ln502_fu_355_p2 <= "1" when (trunc_ln502_fu_352_p1 = ap_const_lv2_0) else "0";
    icmp_ln507_fu_361_p2 <= "1" when (trunc_ln502_fu_352_p1 = ap_const_lv2_1) else "0";
    icmp_ln539_fu_447_p2 <= "1" when (i_0_reg_194 = ap_const_lv10_27E) else "0";
    offset_B_fu_440_p2 <= std_logic_vector(unsigned(offset_B_0_reg_206) + unsigned(ap_const_lv16_F));
    offset_S_1_fu_397_p3 <= 
        ap_const_lv10_0 when (icmp_ln489_fu_391_p2(0) = '1') else 
        offset_S_fu_380_p2;
    offset_S_fu_380_p2 <= std_logic_vector(unsigned(ap_const_lv10_1) + unsigned(i_0_reg_194));
    output_vec_address0 <= grp_scalar_vector_mul_fu_309_output_vec_address0;
    output_vec_address1 <= grp_scalar_vector_mul_fu_309_output_vec_address1;

    output_vec_ce0_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op84_call_state5, ap_predicate_op88_call_state5, ap_predicate_op91_call_state5, ap_predicate_op94_call_state5, ap_predicate_op97_call_state5, ap_predicate_op101_call_state5, grp_scalar_vector_mul_fu_309_output_vec_ce0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)))) then 
            output_vec_ce0 <= grp_scalar_vector_mul_fu_309_output_vec_ce0;
        else 
            output_vec_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_vec_ce1_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op84_call_state5, ap_predicate_op88_call_state5, ap_predicate_op91_call_state5, ap_predicate_op94_call_state5, ap_predicate_op97_call_state5, ap_predicate_op101_call_state5, grp_scalar_vector_mul_fu_309_output_vec_ce1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)))) then 
            output_vec_ce1 <= grp_scalar_vector_mul_fu_309_output_vec_ce1;
        else 
            output_vec_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_vec_d1 <= grp_scalar_vector_mul_fu_309_output_vec_d1;

    output_vec_we1_assign_proc : process(ap_CS_fsm_state5, ap_predicate_op84_call_state5, ap_predicate_op88_call_state5, ap_predicate_op91_call_state5, ap_predicate_op94_call_state5, ap_predicate_op97_call_state5, ap_predicate_op101_call_state5, grp_scalar_vector_mul_fu_309_output_vec_we1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op101_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op97_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op94_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op91_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op88_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op84_call_state5 = ap_const_boolean_1)))) then 
            output_vec_we1 <= grp_scalar_vector_mul_fu_309_output_vec_we1;
        else 
            output_vec_we1 <= ap_const_logic_0;
        end if; 
    end process;


    seed_A_separated_address0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op32_call_state2, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_predicate_op87_call_state5, ap_predicate_op96_call_state5, grp_shake128_10240_fu_234_input_r_address0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            seed_A_separated_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op87_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            seed_A_separated_address0 <= grp_shake128_10240_fu_234_input_r_address0;
        else 
            seed_A_separated_address0 <= "XXXX";
        end if; 
    end process;

    seed_A_separated_address1 <= grp_shake128_10240_fu_234_input_r_address1;

    seed_A_separated_ce0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op32_call_state2, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_predicate_op87_call_state5, ap_predicate_op96_call_state5, grp_shake128_10240_fu_234_input_r_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            seed_A_separated_ce0 <= ap_const_logic_1;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op87_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            seed_A_separated_ce0 <= grp_shake128_10240_fu_234_input_r_ce0;
        else 
            seed_A_separated_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    seed_A_separated_ce1_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op32_call_state2, ap_CS_fsm_state5, ap_predicate_op87_call_state5, ap_predicate_op96_call_state5, grp_shake128_10240_fu_234_input_r_ce1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op96_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op87_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op32_call_state2 = ap_const_boolean_1)))) then 
            seed_A_separated_ce1 <= grp_shake128_10240_fu_234_input_r_ce1;
        else 
            seed_A_separated_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    seed_A_separated_d0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_S_1_fu_397_p3),16));

    seed_A_separated_we0_assign_proc : process(begin_read_read_fu_144_p2, ap_CS_fsm_state3, icmp_ln486_fu_374_p2)
    begin
        if (((begin_read_read_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln486_fu_374_p2 = ap_const_lv1_0))) then 
            seed_A_separated_we0 <= ap_const_logic_1;
        else 
            seed_A_separated_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln539_fu_453_p3 <= 
        ap_const_lv16_0 when (icmp_ln539_fu_447_p2(0) = '1') else 
        ap_phi_mux_offset_B_3_phi_fu_221_p8;

    sk_address0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, ap_predicate_op35_call_state2, ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op90_call_state5, ap_predicate_op93_call_state5, ap_predicate_op100_call_state5, grp_frodo_unpack_8_fu_293_in_r_address0, grp_read_S_fu_325_in_r_address0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op90_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op35_call_state2 = ap_const_boolean_1)))) then 
            sk_address0 <= grp_read_S_fu_325_in_r_address0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op83_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)))) then 
            sk_address0 <= grp_frodo_unpack_8_fu_293_in_r_address0;
        else 
            sk_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    sk_ce0_assign_proc : process(ap_CS_fsm_state2, ap_predicate_op30_call_state2, ap_predicate_op35_call_state2, ap_CS_fsm_state5, ap_predicate_op83_call_state5, ap_predicate_op90_call_state5, ap_predicate_op93_call_state5, ap_predicate_op100_call_state5, grp_frodo_unpack_8_fu_293_in_r_ce0, grp_read_S_fu_325_in_r_ce0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op100_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op90_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op35_call_state2 = ap_const_boolean_1)))) then 
            sk_ce0 <= grp_read_S_fu_325_in_r_ce0;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op93_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_predicate_op83_call_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op30_call_state2 = ap_const_boolean_1)))) then 
            sk_ce0 <= grp_frodo_unpack_8_fu_293_in_r_ce0;
        else 
            sk_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln467_fu_336_p1 <= use_A(2 - 1 downto 0);
    trunc_ln486_fu_370_p1 <= i_0_reg_194(1 - 1 downto 0);
    trunc_ln502_fu_352_p1 <= use_A(2 - 1 downto 0);
    trunc_ln524_fu_367_p1 <= n(10 - 1 downto 0);
    zext_ln488_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_194),64));
    zext_ln514_1_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln514_fu_414_p2),18));
    zext_ln514_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_B_0_reg_206),17));
    zext_ln533_1_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln533_fu_429_p2),18));
    zext_ln533_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_B_0_reg_206),17));
end behav;
